_BASE_: "../Base-TESTRswinv1.yaml"
MODEL:
  # BATEXT:
  #   USE_AET: True
  #   VOC_SIZE: 5462
  #   CUSTOM_DICT: "chn_cls_list"
  TRANSFORMER:
    INFERENCE_TH_TEST: 0.7
    VOC_SIZE: 5463
    # NUM_CHARS: 100
    USE_POLYGON: True
    NUM_CTRL_POINTS: 16
    LOSS:
      POINT_TEXT_WEIGHT: 4.0
DATASETS:
  TRAIN: ("ctw1500_word_poly_train",)
  TEST: ("ctw1500_word_poly_test",)
INPUT:
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TRAIN: 1333
TEST:
  USE_LEXICON: True
  LEXICON_TYPE: 1
  WEIGHTED_EDIT_DIST: False

