_BASE_: "../Base-TESTRswinv1.yaml"
DATASETS:
  TRAIN: ("totaltext_poly_train",)
  TEST: ("totaltext_poly_val",)
MODEL:
  # BATEXT:
  #   USE_AET: True
  #   VOC_SIZE: 5462
  #   CUSTOM_DICT: "chn_cls_list"
  TRANSFORMER:
    USE_POLYGON: True
    NUM_CTRL_POINTS: 16
    VOC_SIZE: 5463
    #NUM_CHARS: 100
    LOSS:
      POINT_TEXT_WEIGHT: 4.0
TEST:
  USE_LEXICON: True
  LEXICON_TYPE: 1