_BASE_: "../Base-TESTRswinv1.yaml"
DATASETS:
  #TRAIN: ("mltbezier_word_poly_train", "totaltext_poly_train", "syntext1_poly_train", "syntext2_poly_train", "icdar2015_train",) 
  #TRAIN: ("syntext1_poly_train", "syntext2_poly_train", )
  TRAIN: ("vintext_train", "vintext_val", )
  TEST: ("vintext_test",)
  #TEST: ("under",)
MODEL:
  TRANSFORMER:
    INFERENCE_TH_TEST: 0.5
    USE_POLYGON: True
    NUM_CTRL_POINTS: 16
    NUM_CHARS: 100
    VOC_SIZE: 105
    LOSS:
      POINT_TEXT_WEIGHT: 4.0
