_BASE_: "../Base-TESTRswinv1.yaml"
DATASETS:
  TRAIN: ("rects_train",)
  TEST: ("icdar2015_test",)
  # TEST: ("rects_test",)
MODEL:
  # BATEXT:
    # USE_AET: True
    # VOC_SIZE: 5462
    # CUSTOM_DICT: "chn_cls_list"
  TRANSFORMER:
    USE_POLYGON: True
    NUM_CTRL_POINTS: 16
    VOC_SIZE: 5463
    # NUM_CHARS: 100
    LOSS:
      POINT_TEXT_WEIGHT: 4.0
TEST:
  USE_LEXICON: True
  LEXICON_TYPE: 3
  WEIGHTED_EDIT_DIST: True
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 1000, 1200, 1400)
  MAX_SIZE_TRAIN: 2333
  MIN_SIZE_TEST: 1440
  MAX_SIZE_TEST: 4000
